### ISSUE TITLE
QGIS crashes when zooming to a group

### ISSUE THREAD

**Issue by danielAtLINZ** [qgis/QGIS#31476]
PostGIS version:
```
# select PostGIS_Full_Version();
POSTGIS="2.5.2 r17328" [EXTENSION] PGSQL="100" GEOS="3.7.0-CAPI-1.11.0 3.7.1" SFCGAL="1.3.2" PROJ="Rel. 4.9.3, 15 August 2016" GDAL="GDAL 2.2.4, released 2018/03/19" LIBXML="2.7.8" LIBJSON="0.12" LIBPROTOBUF="1.2.1" TOPOLOGY RASTER
```

Test data:
```
# select topology.CreateTopology('zoom_to_crash', 4167, 0.0);

# select topology.TopoGeo_AddLineString('zoom_to_crash', ST_geomfromtext('LINESTRING (173.811165705164 -45.1233231220066, 173.813711914836 -45.1233231220066)', 4167));
# select topology.TopoGeo_AddLineString('zoom_to_crash', ST_geomfromtext('LINESTRING (173.812566120484 -45.1243112299339, 173.812566120484 -45.1225146700661)', 4167));
```

Steps to reproduce:
1. Startup QGIS (3.4.10-Madeira - refer crash dump below for more info)
2. Select Database --> DB Manager...
3. From the Providers pane navigate to the zoom_to_crash schema and select/highlight it
4. Select Schema --> TopoViewer (this should create/add several layers to the Layers pane, with groupings named Faces, Nodes, and Edges)
5. In the Layers pane, select the Nodes layer group to display the context/pull-down menu (usually right click)
6. Select Zoom to Group 

### Crash Report

**Crash ID**: 99732b69c6a4a7737cabba1b090bdfa00f53a332

**Stack Trace**
QgsLayerTreeViewDefaultActions::zoomToLayers :
QgsLayerTreeViewDefaultActions::zoomToGroup :
QgsLayerTreeViewDefaultActions::zoomToGroup :
QMetaObject::activate :
QAction::activate :
QMenu::actionGeometry :
QMenu::actionGeometry :
QMenu::mouseReleaseEvent :
QWidget::event :
QMenu::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
CallWindowProcW :
DispatchMessageW :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QMenu::exec :
QgsLayerTreeView::contextMenuEvent :
QWidget::event :
QFrame::event :
QAbstractItemView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
CallWindowProcW :
DispatchMessageW :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

**QGIS Info**
QGIS Version: 3.4.10-Madeira
QGIS code revision: 3d97aaae88
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.16299

**Comment by nirvn** [comment]
I can't replicate the crash on QGIS master (3.9) using the test data mentioned above.

**Comment by palmerj** [comment]
Hi @danielAtLINZ @strk likely fixed this issue in master. Are you able to try a nightly build to see if that resolves it

**Comment by strk** [comment]
The issue I fixed was fixed both in master and 3.4 branch, but I'm not sure it was related with the crash.
I'm building from the 3.4 branch to try at reproducing this.

**Comment by strk** [comment]
For the record, the fix @palmerj is talking about is https://github.com/qgis/QGIS/pull/31324 which was indeed added _after_ the final 3.4.10 version you're using, @danielAtLINZ .

That bug resulted in some layers (including node layer) to only exist in layer group w/out ever being added to map canvas. In my tests there was no "zoom to layer" item showing up when selecting the layer itself.

More background: https://lists.osgeo.org/pipermail/qgis-developer/2019-August/058303.html

Surely trying with a nightly snapshot, or 3.4.12 (not out yet), will help finding out.

**Comment by strk** [comment]
Ok I just tested with current tip of release-3_4 branch and it actually doesn't crash for me.
@danielAtLinz are you able to test that version  yourself ?

**Comment by danielAtLINZ** [comment]
Update:
Will wait for 3.4.12 release to re-test.

I could still reproduce the issue, with both 3.4.11 and 3.8.2.

**Comment by strk** [comment]
@danielAtLINZ did you have a chance to test with newer versions ? We're working on bugfixes for 3.12 now...

**Comment by danielAtLINZ** [comment]
Sorry @strk , had to find a postgres/postGIS+topology setup to re-test against 3.4.15-Madeira.

Okay, so I can confirm it no longer crashes for the specific test case.

Closing issue.
