### ISSUE TITLE
Stops responding when adding a legend

### ISSUE THREAD

**Issue by ThatJCB** [qgis/QGIS#31872]
This is on maps with lots of layers and categories. These are mainly included from OS Openmap vector data.

QGIS version 3.8.2-Zanzibar
Windows 10

I've tried it on a couple of maps and my guess is that it enumerates every possible layer and category, which is taking some time!

**Comment by ThatJCB** [comment]
It has the same behaviour in 3.8.3

**Comment by gioman** [comment]
Can you be a little more specific? it is about adding a legend in a print layout?

**Comment by nyalldawson** [comment]
Possibly fixed by https://github.com/qgis/QGIS/pull/31866 ?

**Comment by ThatJCB** [comment]
Yes. In the Print Layout.
Using the Add Legend icon or from the menu.

It works on maps with only a few categories but, I am guessing, if the map
has lots of categories it gets stuck.
I've left it for over 15 minutes and it still does not complete.

It just draws a fine red border.

My map has data Exported from Open Street Map and the UK Ordnance Survey
OpenMap Local and Boundaries in Vector ESRI shape format for square TL from
the UK.

https://www.ordnancesurvey.co.uk/opendatadownload/products.html

Regards
__
John C. Brown

**Comment by ThatJCB** [comment]
> Possibly fixed by #31866 ?

Once that's merged in, I'll try a nightly build to see if it helps.
Thank you

**Comment by gioman** [comment]
Assuming fixed.
