### ISSUE TITLE
QGIS 3.10 Download of capabilities failed: SSL handshake failed

### ISSUE THREAD

**Issue by giswgjs** [qgis/QGIS#32920]
I try to acces a WMS under https://maps.dwd.de/geoserver/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetCapabilities from QGIS 3.10.0 and get the error message **Download of capabilities failed: SSL handshake failed**.

![grafik](https://user-images.githubusercontent.com/17158239/69036299-dee60a00-09e5-11ea-9e05-ec012c5f6603.png)

Accessing **_http_** WMSses works straight and the service can be accesses from 3.4.13 LTR without any problem.

(?) possibly related: https://github.com/qgis/QGIS/issues/31675

**Comment by gioman** [comment]
The error I get is

![Screenshot_20191118_083901](https://user-images.githubusercontent.com/1951107/69037108-21581880-09df-11ea-83a3-a446d95e4a7e.png)

if you "save and ignore" you stop to get it and the service works.

I think that this may have been addressed by https://github.com/qgis/QGIS/issues/32861#issuecomment-554323520

**Comment by nirvn** [comment]
@giswgjs , can you check whether your user profile (Settings > User Profiles > Open Active Profile Folder) has a qgis-auth.db file in it?

Also, if you are able to install a development build on your system via the package-based osgeo4w installer, you should give that a try, the underlying issue might have been addressed.

**Comment by giswgjs** [comment]
I just upgraded to the latest nightly build (3.11.0-15) and the issue still persists. I had a qgis-auth.db in my profile which I just erased.

**Comment by enricofer** [comment]
I tested QGIS nightly build f9f00d3388 that fixes issue https://github.com/qgis/QGIS/issues/32507 but not this.

**Comment by hugbe8** [comment]
os: Windows 10
version dev 3.11.0 and release 3.10.0

I have result the ssl handshake with proposed [Manually adding configuration](https://docs.qgis.org/3.4/en/docs/user_manual/auth_system/auth_workflows.html).  But i have still the "QGIS Download of capabilities" in trouble in version: dev 3.11.0 and release 3.10.0.
Curiously somes connections seems to work in the exploration panel while nothing works through the data addition manager (...WMS). It appears that the handler of data does not use credentials from the authentication manager.

No problem in LTR 3.4.13 with the same configuration d'authentification.

**Comment by gioman** [comment]
Still true on QGIS master/3.13.

**Comment by elpaso** [comment]
@agiudiceandrea did you manage to configure `/etc/ssl/openssl.cnf` to SECLEVEL=1 and connect to the NASA WMS with QGIS? I tried without success.

**Comment by agiudiceandrea** [comment]
Hi @elpaso, IIRC yes: I followed the advice at https://askubuntu.com/questions/1233186/ubuntu-20-04-how-to-set-lower-ssl-security-level/1233456#1233456 and https://bugs.launchpad.net/ubuntu/+source/openssl/+bug/1864689 (comment 13).
I cannot verify if the workaround is still valid, as I currently do not have access to an Ubuntu 20.04 system.

Have you tried to connect to the server via CLI with `openssl s_client -connect gibs.earthdata.nasa.gov:443 -cipher DEFAULT@SECLEVEL=1`? Does it connect?

Anyway, about one years ago I reported the issue to support@earthdata.nasa.gov. After some months they managed to fix their uat.gibs.earthdata.nasa.gov testing site updating the signing digest used during the SSL handshake protocol negotiation from SHA1 to SHA256.
But it seem they still haven't been able to fix the issue with the main server at gibs.earthdata.nasa.gov.

More info in this thread https://www.mail-archive.com/qgis-user@lists.osgeo.org/msg45941.html

**Comment by elpaso** [comment]
> Hi @elpaso, IIRC yes: I followed the advice at https://askubuntu.com/questions/1233186/ubuntu-20-04-how-to-set-lower-ssl-security-level/1233456#1233456 and https://bugs.launchpad.net/ubuntu/+source/openssl/+bug/1864689 (comment 13).
> I cannot verify if the workaround is still valid, as I currently do not have access to an Ubuntu 20.04 system.
> 
> Have you tried to connect to the server via CLI with `openssl s_client -connect gibs.earthdata.nasa.gov:443 -cipher DEFAULT@SECLEVEL=1`? Does it connect?

Yes, it does and now that I fixed also `/etc/ssl/openssl.cnf` it also connects without `-cypher`. 

But I still cannot connect from within QGIS.

> 
> Anyway, about one years ago I reported the issue to [support@earthdata.nasa.gov](mailto:support@earthdata.nasa.gov). After some months they managed to fix their uat.gibs.earthdata.nasa.gov testing site updating the signing digest used during the SSL handshake protocol negotiation from SHA1 to SHA256.
> But it seem they still haven't been able to fix the issue with the main server at gibs.earthdata.nasa.gov.
> 
> More info in this thread https://www.mail-archive.com/qgis-user@lists.osgeo.org/msg45941.html

Thank you for the information!

**Comment by elpaso** [comment]
@agiudiceandrea it is working now from QGIS after double-checking https://askubuntu.com/questions/1233186/ubuntu-20-04-how-to-set-lower-ssl-security-level/1233456#1233456

**Comment by agiudiceandrea** [comment]
@elpaso the main GIBS server at gibs.earthdata.nasa.gov now uses a SHA256 peer signing digest, so it should be now possible to use the WMSs at gibs.earthdata.nasa.gov on Ubuntu 20.04 LTS without the need to lower the openssl default security level setting.
