### ISSUE TITLE
Cannot normalize transform between EPSG:3857 and EPSG:27700

### ISSUE THREAD

**Issue by SteveLowman** [qgis/QGIS#33154]
In QGIS 3.10, when an xyz tile of EPSG:3857 is attempting to render in a project of EPSG:27700 (British National Grid), it renders only a few tiles along the west coast of Scotland.

A series of "CRITICAL" messages are generated in the General log, stating "Cannot normalize transform between EPSG:3857 and EPSG:27700", and the same but "... between EPSG:27700 and EPSG:3857".

Before reproducing this error, it is important to make sure you have the most recent transformation file in your 'proj' folder - that is 'OSTN15_NTv2_OSGBtoETRS.gsb'.

(https://gis.stackexchange.com/questions/342280/qgis-3-10-projection-error-using-bng27700) describes the same problem, and the forum conversation concludes with the OP asking how he can report the bug here (22nd November, but he doesn't seem to have done so yet).

Steps to reproduce:

1. Start a new project, and add the OpenStreetMap xyz tile. It will render with no problem in EPSG:3857.

2. Change the project CRS to EPSG:27700. You will probably get a dialog asking to choose the transformation. I have tried the nice new one, and the 2 metre error one that is the second choice, but the problem occurs with either of those.

3. Having completed the change of CRS and chosen the transformation, then do 'zoom to layer', and it will show you a strip of western Scotland and the east coast of Northern Ireland.

4. Look in the General log, and you will see the series of CRITICAL messages as described above.

Attached are image files to show the dialog for choosing the transformation, and then the map canvas, browser panel, and General log, with the narrow strip of tiles and the messages there.

I don't think it would make sense to include an attached project, but I will do so on request.

Thanks

Steve

![Choose transformation dialog](https://user-images.githubusercontent.com/8450382/69874703-92d37900-12b3-11ea-9215-53a88ccd57cc.png)
![Cannot normalize transform - general log](https://user-images.githubusercontent.com/8450382/69874769-b3033800-12b3-11ea-9a0a-621c4418d772.png)

**Comment by gioman** [comment]
Duplicate of https://github.com/qgis/QGIS/issues/30643 ?

**Comment by SteveLowman** [comment]
Thanks, I do not think it is a duplicate of #30643, which was essentially resolved by ensuring there was a warning to add the .gsb file, which worked okay, apparently, back in July.

The more recent comments there from 9 days ago may be related, as one of them is saying .gsb transformations are causing a problem, but they are describing a bug that is quite different to the originally reported one. If the real bug is that .gsb transformations are not working, then perhaps the title of this bug should be changed, or a perhaps new bug should be raised for that issue and then close this one.

And then, there is the link to #12 there, which may or may not be relevant, but sorry it goes beyond my level of technical knowledge.

**Comment by SteveLowman** [comment]
Thanks. Do you need any more feedback for now?

**Comment by nyalldawson** [comment]
This is likely fixed in 3.10.1 - please reopen if it can reproduce under this release

**Comment by SteveLowman** [comment]
Please re-open this. The same stuff is happening in 3.10.1 and in 3.11 master (0d84e35839).

The differences are that 3.11 went through a procedure of installing the .gsb file, which never happened in 3.10, and there are none of the General warnings in 3.11, but they are still happening in 3.10.1.

However, 3.11 is still rendering only the strip of EPSG:3857 tiles down the west coast of Scotland.

Thanks

**Comment by nyalldawson** [comment]
I can't reproduce using gdal + proj master:

![image](https://user-images.githubusercontent.com/1829991/71058420-8607be00-21ab-11ea-84e5-fc56593be474.png)

or a more sensible example:

![image](https://user-images.githubusercontent.com/1829991/71058515-d121d100-21ab-11ea-8285-a306713e158f.png)

**Comment by nyalldawson** [comment]
(in other words -- it was likely something fixed in proj master)

**Comment by SteveLowman** [comment]
Sorry for ignorance, but is it possible to install proj master with QGIS 3.10? Is this something a user who is not a developer can do? Is there a link to instructions anywhere?

**Comment by jef-n** [comment]
Depends on you platform.  The nightly of 3.10 in OSGeo4W (qgis-rel-dev) is built with the nightlies of proj and GDAL - otherwise you have to wait for an update in OSGeo4W of a release of proj that includes the fix.

**Comment by SteveLowman** [comment]
Okay, thanks, I'll try a nightly release then.

**Comment by SteveLowman** [comment]
Does anyone know is this OSGeo4W update of proj scheduled to coincide with any particular release on the QGIS schedule? Just wondering how long I would need to keep using nightly build releases.

**Comment by SteveLowman** [comment]
I installed the 3.10.1-5 in qgis-rel-dev, and I still get the same issue. The image here shows which proj library it is using. Please advise further if possible. Thanks.
![3101nightlyabout](https://user-images.githubusercontent.com/8450382/71082759-8db66b00-2189-11ea-9e39-f2f44bf4d003.png)

**Comment by SteveLowman** [comment]
So, can we open this again to try to get the fix incorporated into QGIS 3.10, etc.?
Otherwise/also, can anyone say what version of proj includes this fix, if it does not work in proj 6.3.0, and which, if any, version of QGIS actually includes the fix?

**Comment by SteveLowman** [comment]
I tried the install again, and it was installing with proj 6.3.0-20, upgraded from 6.3.0-19, but still the same issue. I do not understand why this is not reproduceable.

**Comment by SteveLowman** [comment]
> (in other words -- it was likely something fixed in proj master)

Please tell me what version of qgis, gdal, and proj is working for you.

**Comment by arc12** [comment]
I have the same issue as in the initial issue posting.
Previously QGIS 3.6 was quite happy.
Installed 3.10.1 (not the OSGeo4W package).
Now doing as OP indicates.

**Comment by nyalldawson** [comment]
You'll need to wait for 3.10.2, that includes the fixes

**Comment by david-laverty** [comment]
I am having this same issue still when using the following qgis-rel-dev-bin-g7 version of QGIS.
![image](https://user-images.githubusercontent.com/48278498/72143135-13df5f00-338e-11ea-9a14-d7f7744a844b.png)

The issue occurs if you add the recommended OSTN15_NTv2_OSGBtoETRS.gsb from proj-datumgrid-europe-1.5.zip

To reproduce this error 1st add a layer in BNG then try to add a WMS layer with EPSG:3857, I used Google Roads. This produces the exact same issue as OP running on the latest PROJ / GDAL available from OSGeo4W. 
Without using this transformation and applying 2nd one in the transformations list (with accuracy of 2m instead of 1m) list the WMS layer loads fine but is slighty off in its positioning when compared to a accurately referenced BNG layer. 

Is there anyway at present to fix this issue running the latest nightly builds?

**Comment by nirvn** [comment]
@david-laverty , can you provide test data to replicate your issue?

**Comment by SteveLowman** [comment]
> @david-laverty , can you provide test data to replicate your issue?

Nyall Dawson has already stated we should wait for 3.10.2 to test for a fix. It is only a few days to wait.

Anyway, maybe test data are not so useful for this. You just need to add the the OSTN15_NTv2_OSGBtoETRS.gsb from proj-datumgrid-europe-1.5.zip, then set your project file CRS to EPSG:27700, and then try adding a WMS with EPSG:3857.

**Comment by david-laverty** [comment]
Surely the issue will still be present on the latest release of 3.10.2 if it is using the latest PROJ v7 which I currently tested the issue on?

I was just making the dev's aware that the issue is still present on PROJ v7.0.0 using the latest nightly build which in theory will be QGIS 3.10.2 when released

To test please load in the following shapefile (which will set the project CRS to EPSG:27700) and then add a wms layer with ESPG:3857. eg. Google Roads - https://mt1.google.com/vt/lyrs=m&x={x}&y={y}&z={z}

With the OSTN15_NTv2_OSGBtoETRS.gsb file added to the proj folder suggested, select the 1m accuracy transformation which uses this .gsb file and it should reproduce the error the OP is describing

[BNG WMS Issue.zip](https://github.com/qgis/QGIS/files/4045398/BNG.WMS.Issue.zip)

**Comment by SteveLowman** [comment]
@david-laverty Thanks, if what you say is correct, then this issue should be re-opened.

**Comment by BensonArizona** [comment]
I have a standard installation of QGIS 3.10.1 without selecting or adding any special files or options.  

1) Open a new project (with default CRS set to EPSG:3857) and add a WMS (in this case OpenStreetMap from XYZ Tiles).  It doesn't matter whether you zoom into the UK or not.

2) Change CRS to EPSG:27700.

It now shows only the same thin vertical strip at the west of Scotland as advised by Steve Lowman and others above.  This happens for me whether or not you select the CRS option to "Ask for datum transformation if several are available"; and if that option is set then regardless of the chosen transformation.

If you then convert to another localised CRS (I chose EPSG:8687 Slovenia at random) then it seems to work just fine.

Given what has been said above, it doesn't seem likely that this issue will be fixed in 3.10.2 as it is apparently not been possible for the dev's to reproduce it (has it?).

Please can this be re-opened until it has been established that it is indeed fixed?

**Comment by gioman** [comment]
> Surely the issue will still be present on the latest release of 3.10.2 if it is using the latest PROJ v7 which I currently tested the issue on?
> 
> I was just making the dev's aware that the issue is still present on PROJ v7.0.0 using the latest nightly build which in theory will be QGIS 3.10.2 when released
> 
> To test please load in the following shapefile (which will set the project CRS to EPSG:27700) and then add a wms layer with ESPG:3857. eg. Google Roads - [https://mt1.google.com/vt/lyrs=m&x={x}&y={y}&z={z}](https://mt1.google.com/vt/lyrs=m&x=%7Bx%7D&y=%7By%7D&z=%7Bz%7D)
> 
> With the OSTN15_NTv2_OSGBtoETRS.gsb file added to the proj folder suggested, select the 1m accuracy transformation which uses this .gsb file and it should reproduce the error the OP is describing
> 
> [BNG WMS Issue.zip](https://github.com/qgis/QGIS/files/4045398/BNG.WMS.Issue.zip)

@david-laverty I just tested the above and what will be the next 3.10.2 (on Windows) and it all works without errors.

**Comment by david-laverty** [comment]
Great news. I look forward to the latest 3.10.2 update now. Thanks very much for taking the time to test this. It is very much appreciated



Sent from my Samsung Galaxy smartphone.



-------- Original message --------

**Comment by david-laverty** [comment]
@gioman I have installed 3.10.2 using OSGeo4W installer just now and I have installed OSTN15_NTv2_OSGBtoETRS.gsb as requested by QGIS for the ideal 1m transformation accuracy but I am still getting the same problem as before when loading 1st the BNG EPSG: 27700 layer followed by the EPSG:3857. What am I doing that you are not to resolve this issue? do you have any idea?
Before adding the gsb file the layers are off alignment
![image](https://user-images.githubusercontent.com/48278498/72721503-1dc64680-3b74-11ea-8f5c-d55948a8baa1.png)
After adding the gsb file the thin strip off western Scotland is the only visible part of the WMS layer for Google roads
![image](https://user-images.githubusercontent.com/48278498/72721589-52d29900-3b74-11ea-8ef8-7acc427fa775.png)

**Comment by SteveLowman** [comment]
> @gioman I have installed 3.10.2 using OSGeo4W installer just now and I have installed OSTN15_NTv2_OSGBtoETRS.gsb as requested by QGIS for the ideal 1m transformation accuracy but I am still getting the same problem as before when loading 1st the BNG EPSG: 27700 layer followed by the EPSG:3857. What am I doing that you are not to resolve this issue? do you have any idea?
> Before adding the gsb file the layers are off alignment
> After adding the gsb file the thin strip off western Scotland is the only visible part of the WMS layer for Google roads

@david-laverty There you have used proj 6.2.1 and gdal 3.0.2. I think we need to test 3.10.2 with the latest dev versions of the two libraries. I will try this when I get time.

**Comment by gioman** [comment]
So let's try to clear things:

the ticket is/was about the error message "Cannot normalize transform between EPSG:3857 and EPSG:27700" when reprojecting to 27700 using OSTN15_NTv2_OSGBtoETRS.gsb.

What I am seeing here, on a clean 3.10.2 installation (with OSgeo4W) on a clean Windows system, is that the message does not show anymore.

Steps I follow:

I add the following layer (that has CRS 3857)

[test.zip](https://github.com/qgis/QGIS/files/4086362/test.zip)

then set the CRS 27770 for the project choosing OSTN15_NTv2_OSGBtoETRS.gsb as option.

No such "Cannot normalize transform between EPSG:3857 and EPSG:27700" message show anymore.

Yes, there is an issue in reprojecting WMS/XYZ layers with the same method, I also see "the strip", but this only if using the datum shift grid, not is using one of the less precise methods.

I think that the "strip" issue should be reported as a separate issue, but this one seems fixed to me and should stay closed... I think.

**Comment by SteveLowman** [comment]
@gioman Which proj and gdal versions have you installed with 3.10.2?

**Comment by david-laverty** [comment]
@SteveLowman I have now tried using GDAL 3.1.0dev and PROJ 7.0.0 on 3.10.2 Still producing the same "strip" output for me. 
![image](https://user-images.githubusercontent.com/48278498/72734205-2711dc00-3b91-11ea-98b0-8a488f75716b.png)

**Comment by gioman** [comment]
> Still producing the same "strip" output for me.

@david-laverty this is a separate issue. This ticket is about the "Cannot normalize transform between EPSG:3857 and EPSG:27700" message. The datum transformation using the NTv2 grid now works without error messages, and it works ok for vectors and rasters in general (as far as I can see, I do not work with UK data). There is this issue while reprojecting WMS layers, true, but please file it in a new ticket.

**Comment by gioman** [comment]
> @gioman Which proj and gdal versions have you installed with 3.10.2?

@SteveLowman 

![Screenshot_20200120_144606](https://user-images.githubusercontent.com/1951107/72735368-9983bb80-3b93-11ea-81d9-cfa5943449a7.png)

**Comment by SteveLowman** [comment]
Yes, I agree. In 3.10.2 with gdal 3.1.0 dev and proj 7.0.0, the problem is the there with the OSTN15_NTv2_OSGBtoETRS.gsb, but the same issue is not occurring now with the less precise transformation files.

So, the issue seems to be specific to OSTN15_NTv2_OSGBtoETRS.gsb, and we should open a new ticket for this. We should also test with EPSG:3857 layers that are not WMS to ascertain whether other source data formats are affected.

**Comment by david-laverty** [comment]
I never had any issue with the less precise transformation files, only the 1m accuracy one which required the gsb file. Did you have the issue when the gsb file was removed from your system using the lower accuracy transformation? My work around was to use the 2m accuracy transformation with the gsb file removed from my PROJ folder and it worked ok. Do you have a EPSG:3857 layer that's not a WMS / xyz file?

**Comment by gioman** [comment]
> Do you have a EPSG:3857 layer that's not a WMS / xyz file?

https://github.com/qgis/QGIS/files/4086362/test.zip

**Comment by david-laverty** [comment]
No problems with that tif file using EPSG:3857. That's with both GDAL 3.0.2 / PROJ 6.2.1 & GDAL 3.1.0dev and PROJ 7.0.0 running on QGIS 3.10.2. Windows 10
