### ISSUE TITLE
Postgresql rasters do not load

### ISSUE THREAD

**Issue by Tetranos** [qgis/QGIS#35259]
Hi,

I've imported a raster into PostgreSQL using raster2pgsql. This raster is correctly displayed in QGis 3.10 whereas QGis 3.12 says the layer is not valid, see attached file.

Regards,
![raster 3 10 vs 3 12](https://user-images.githubusercontent.com/795919/77302591-dbdf8b00-6cf1-11ea-934d-35a379e63cb7.JPG)

**Comment by jgrocha** [comment]
@Tetranos The way both versions handles the postgis raster is different. 3.10 uses GDAL and 3.12 uses a new native provider.

If you open the project in QGIS 3.12 (created by QGIS 3.10) you might not see the raster. 

Can you try to create an empty project in QGIS 3.12 and add the raster to it?

**Comment by elpaso** [comment]
@jgrocha that's not correct: PG raster layers in projects created with older versions of QGIS will still be opened with GDAL provider instead of using the new pgraster.

**Comment by elpaso** [comment]
@Tetranos you may be hitting a packaging bug where in windows packages the new 'postgresraster' provider DLL was not added. This was fixed a few weeks ago.

**Comment by jgrocha** [comment]
> @jgrocha that's not correct: PG raster layers in projects created with older versions of QGIS will still be opened with GDAL provider instead of using the new pgraster.

Thank you @elpaso for the correction.

**Comment by Gustry** [comment]
@Tetranos Update your QGIS 3.12 to the latest point release.

**Comment by Tetranos** [comment]
> Can you try to create an empty project in QGIS 3.12 and add the raster to it?

This was already the case with my screenshot. I've set 3.10 and 3.12 side to side but I've created a new project and add the raster.

> @Tetranos you may be hitting a packaging bug where in windows packages the new 'postgresraster' provider DLL was not added. This was fixed a few weeks ago.

I'll try that.

**Comment by Tetranos** [comment]
I've :
- uninstalled 3.12
- downloaded 3.12 using this link : https://qgis.org/downloads/QGIS-OSGeo4W-3.12.0-2-Setup-x86_64.exe
- reinstalled 3.12

But It still does not work.

Error message (FR)
"Couche non valide: Raster layer Impossible d'instancier le fournisseur de données 'postgresraster'"

**Comment by Gustry** [comment]
>     * downloaded 3.12 using this link : https://qgis.org/downloads/QGIS-OSGeo4W-3.12.0-2-Setup-x86_64.exe

Still not the latest. 3.12.1 is the latest point release. Links might be updated soon or use nightly build

https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule

**Comment by Tetranos** [comment]
> > ```
> > * downloaded 3.12 using this link : https://qgis.org/downloads/QGIS-OSGeo4W-3.12.0-2-Setup-x86_64.exe
> > ```
> 
> Still not the latest. 3.12.1 is the latest point release. Links might be updated soon or use nightly build
> 
> https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule

Reading @elpaso , looks like it's a Windows package problem and not a bug in the 3.12.0.2...

**Comment by Gustry** [comment]
3.12.1 is out, can you try again?
So Windows package has also been updated.

**Comment by Tetranos** [comment]
> 3.12.1 is out, can you try again?
> So Windows package has also been updated.

3.12.1 Tested and approved. Rasters are correctly displayed!
