### ISSUE TITLE
QGIS 3.10.4 incorrectly reading CRS for MapInfo tables in GDA2020 written by QGIS itself.

### ISSUE THREAD

**Issue by JuanPufleau** [qgis/QGIS#35824]
QGIS 3.10.4 is incorrectly reading CRS for MapInfo tables in GDA2020 written by QGIS itself.
This also happens with MapInfo tables created by MapInfo, FME.   Only a file created with ogr2ogr 3.0.4 is recognised properly.

To reproduce:

Take a QGIS layer, any projection, any format.
/ Layer/ Save As, in MapInfo format and CRS GDA2020 datum (EPSG:7855).
Load the new GDA2020 data into QGIS.
QGIS wrongly identify the datum as EPSG:32755 or as custom datum.

This has been reported as to be solved in 3.10.2, but it's still there in 3.10.4.

**Comment by gioman** [comment]
@JuanPufleau on what platform?

**Comment by nyalldawson** [comment]
It's an upstream issue which was fixed in gdal, but we are waiting for a gdal release before the qgis installs will benefit from this fix

**Comment by JuanPufleau** [comment]
In Windows 10.   

I just tested 3.12, with the same behaviour.

**Comment by gioman** [comment]
> I just tested 3.12, with the same behaviour.

@JuanPufleau https://github.com/qgis/QGIS/issues/35824#issuecomment-615192268

**Comment by meyerlor** [comment]
This issue is still occurring. QGIS 3.22.3, GDAL 3.4.1

Saving a Shape/GPKG/any format layer to EPSG 25832 with QGIS and then opening that exported file results in QGIS "recognizing" the CRS as 32632 - WGS 84 / UTM zone 32N

**Comment by gioman** [comment]
> Saving a Shape/GPKG/any format layer to EPSG 25832 with QGIS and then opening that exported file results in QGIS "recognizing" the CRS as 32632 - WGS 84 / UTM zone 32N

@meyerlor test from the command line, translate/save the vector with ogr2ogr and check the result with ogrinfo.

**Comment by meyerlor** [comment]
### G:\USER\sct\Daten\AAA_Temp\BORIS GVV Markdorf>C:\OSGeo4W\bin\ogrinfo -so -al src.shp
INFO: Open of `src.shp'
      using driver `ESRI Shapefile' successful.

Layer name: src
Metadata:
  DBF_DATE_LAST_UPDATE=2021-12-23
Geometry: Polygon
Feature Count: 296
Extent: (517700.150000, 5281321.899878) - (537137.040000, 5302830.139878)
Layer SRS WKT:
PROJCRS["ETRS89 / UTM zone 32N",
    BASEGEOGCRS["ETRS89",
        ENSEMBLE["European Terrestrial Reference System 1989 ensemble",
            MEMBER["European Terrestrial Reference Frame 1989"],
            MEMBER["European Terrestrial Reference Frame 1990"],
            MEMBER["European Terrestrial Reference Frame 1991"],
            MEMBER["European Terrestrial Reference Frame 1992"],
            MEMBER["European Terrestrial Reference Frame 1993"],
            MEMBER["European Terrestrial Reference Frame 1994"],
            MEMBER["European Terrestrial Reference Frame 1996"],
            MEMBER["European Terrestrial Reference Frame 1997"],
            MEMBER["European Terrestrial Reference Frame 2000"],
            MEMBER["European Terrestrial Reference Frame 2005"],
            MEMBER["European Terrestrial Reference Frame 2014"],
            ELLIPSOID["GRS 1980",6378137,298.257222101,
                LENGTHUNIT["metre",1]],
            ENSEMBLEACCURACY[0.1]],
        PRIMEM["Greenwich",0,
            ANGLEUNIT["degree",0.0174532925199433]],
        ID["EPSG",4258]],
    CONVERSION["UTM zone 32N",
        METHOD["Transverse Mercator",
            ID["EPSG",9807]],
        PARAMETER["Latitude of natural origin",0,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8801]],
        PARAMETER["Longitude of natural origin",9,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8802]],
        PARAMETER["Scale factor at natural origin",0.9996,
            SCALEUNIT["unity",1],
            ID["EPSG",8805]],
        PARAMETER["False easting",500000,
            LENGTHUNIT["metre",1],
            ID["EPSG",8806]],
        PARAMETER["False northing",0,
            LENGTHUNIT["metre",1],
            ID["EPSG",8807]]],
    CS[Cartesian,2],
        AXIS["(E)",east,
            ORDER[1],
            LENGTHUNIT["metre",1]],
        AXIS["(N)",north,
            ORDER[2],
            LENGTHUNIT["metre",1]],
    USAGE[
        SCOPE["Engineering survey, topographic mapping."],
        AREA["Europe between 6┬░E and 12┬░E: Austria; Belgium; Denmark - onshore and offshore; Germany - onshore and offshore; Norway including - onshore and offshore; Spain - offshore."],
        BBOX[38.76,6,84.33,12]],
    ID["EPSG",25832]]
Data axis to CRS axis mapping: 1,2


### G:\USER\sct\Daten\AAA_Temp\BORIS GVV Markdorf>C:\OSGeo4W\bin\ogr2ogr -s_srs EPSG:25832 -t_srs EPSG:25832 dest.tab src.shp

### G:\USER\sct\Daten\AAA_Temp\BORIS GVV Markdorf>C:\OSGeo4W\bin\ogrinfo -so -al dest.tab
INFO: Open of `dest.tab'
      using driver `MapInfo File' successful.

Layer name: dest
Geometry: Unknown (any)
Feature Count: 296
Extent: (517700.150000, 5281321.900000) - (537137.040000, 5302830.140000)
Layer SRS WKT:
PROJCRS["unnamed",
    BASEGEOGCRS["unnamed",
        DATUM["Euref_89",
            ELLIPSOID["GRS 80",6378137,298.257222101,
                LENGTHUNIT["metre",1,
                    ID["EPSG",9001]]]],
        PRIMEM["Greenwich",0,
            ANGLEUNIT["degree",0.0174532925199433,
                ID["EPSG",9122]]]],
    CONVERSION["Transverse Mercator",
        METHOD["Transverse Mercator",
            ID["EPSG",9807]],
        PARAMETER["Latitude of natural origin",0,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8801]],
        PARAMETER["Longitude of natural origin",9,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8802]],
        PARAMETER["Scale factor at natural origin",0.9996,
            SCALEUNIT["unity",1],
            ID["EPSG",8805]],
        PARAMETER["False easting",500000,
            LENGTHUNIT["metre",1],
            ID["EPSG",8806]],
        PARAMETER["False northing",0,
            LENGTHUNIT["metre",1],
            ID["EPSG",8807]]],
    CS[Cartesian,2],
        AXIS["(E)",east,
            ORDER[1],
            LENGTHUNIT["metre",1,
                ID["EPSG",9001]]],
        AXIS["(N)",north,
            ORDER[2],
            LENGTHUNIT["metre",1,
                ID["EPSG",9001]]]]
Data axis to CRS axis mapping: 1,2
gesl: String (12.0)
gena: String `(30.0)`

**Comment by gioman** [comment]
> I'm sorry for the bad formatting. Here it is better:

@meyerlor is ok, but as you see is not a QGIS issue apparently.

**Comment by meyerlor** [comment]
ok, i already opened an GDAL issue here: https://github.com/OSGeo/gdal/issues/5217
