### ISSUE TITLE
QGIS master crash with models

### ISSUE THREAD

**Issue by PedroVenancio** [qgis/QGIS#41671]
I'm getting QGIS crashes on master, when running Models. The same models runs smoothly in 3.16.

After some investigation, I came to two algorithms that gives problems when inside Models: Clip Raster by Mask Layer and Clip Raster by Extent.

Please try this simple model:
[Hillshade.zip](https://github.com/qgis/QGIS/files/6005092/Hillshade.zip)
Inputs are a DTM and the extent to clip the DTM.

You will get a QGIS crash. 

```
Crash ID: 61607a5f47189419c7659d47f98b61aa32c82d05

Stack Trace

QProcess::readAllStandardOutput :
QgsLayoutItemScaleBar::setLabelBarSpace :
QgsLayoutItemScaleBar::setLabelBarSpace :
QgsLayoutItemScaleBar::setLabelBarSpace :
QgsLayoutItemScaleBar::setLabelBarSpace :
QMetaCallEvent::placeMetaCall :
QObject::event :
PyInit__core :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsLayoutItemScaleBar::setLabelBarSpace :
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
qt_plugin_query_metadata :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QgsModelViewMouseHandles::qt_metacall :
QgsModelViewMouseHandles::qt_metacall :
QgsModelViewMouseHandles::qt_metacall :
QgsModelViewMouseHandles::qt_metacall :
QgsModelViewMouseHandles::qt_metacall :
QgsModelViewMouseHandles::qt_metacall :
QObject::qt_static_metacall :
QgsModelViewMouseHandles::qt_metacall :
QgsModelViewMouseHandles::qt_metacall :
QgsLayoutItemScaleBar::setLabelBarSpace :
PyInit__core :
PyDict_MergeFromSeq2 :
PyEval_EvalFrameDefault :
PyObject_GC_Del :
PyFunction_Vectorcall :
PyEval_EvalFrameDefault :
PyFunction_Vectorcall :
PyLong_AsDouble :
PyVectorcall_Call :
PyObject_Call :
PyInit__core :
PyInit__core :
QgsLayoutItemScaleBar::setLabelBarSpace :
QgsLayoutItemScaleBar::setLabelBarSpace :
QgsLayoutItemScaleBar::setLabelBarSpace :
QgsLayoutItemScaleBar::setLabelBarSpace :
QgsLayoutItemScaleBar::setLabelBarSpace :
PyInit__core :
PyDict_MergeFromSeq2 :
PyEval_EvalFrameDefault :
PyObject_GC_Del :
PyEval_EvalFrameDefault :
PyObject_GC_Del :
PyFunction_Vectorcall :
PyLong_AsDouble :
PyVectorcall_Call :
PyObject_Call :
PyInit__gui :
PyInit__gui :
QgsModelViewMouseHandles::qt_metacall :
QgsModelViewMouseHandles::qt_metacall :
QgsModelViewMouseHandles::qt_metacall :
QObject::qt_static_metacall :
QAbstractButton::clicked :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsLayoutItemScaleBar::setLabelBarSpace :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsLayoutItemScaleBar::setLabelBarSpace :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QDialog::exec :
PyInit_QtWidgets :
PyDict_MergeFromSeq2 :
PyEval_EvalFrameDefault :
PyObject_GC_Del :
PyFunction_Vectorcall :
PyLong_AsDouble :
PyVectorcall_Call :
PyObject_Call :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
QObject::qt_static_metacall :
QAbstractItemView::doubleClicked :
QTreeView::mouseDoubleClickEvent :
PyInit__gui :
QWidget::event :
QFrame::event :
QAbstractItemView::viewportEvent :
PyInit__gui :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsLayoutItemScaleBar::setLabelBarSpace :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsLayoutItemScaleBar::setLabelBarSpace :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
QgsDecorationTitleDialog::trUtf8 :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.17.0-Master
QGIS code revision: fa9135792
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.2.1
Running against GDAL: 3.2.1

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19042
```

Running it from command line qgis_process-qgis-dev I get

```
----------------
Inputs
----------------

DTM:    D:/SRTM_PT_25m.tif
Extent: 23888.957800000,81313.275400000,31068.238200000,108893.300200000 [EPSG:3763]
native:hillshade_1:Hillshade:   D:/Shaded.tif

D:\src\osgeo4w\src\qgis-dev\qgis\src\core\qgsmessagelog.cpp(29) : (QgsMessageLog::logMessage) [5924ms] 2021-02-18T18:31:18 Processing[0] gdal_translate -projwin 23888.9578 108893.3002 81313.2754 31068.2382 -of GTiff D:/SRTM_PT_25m.tif C:/Users/PedroVenancio/AppData/Local/Temp/processing_PlqxDO/caaf47333c4e4516abbe642839e8c07e/OUTPUT.tif
GDAL command:
gdal_translate -projwin 23888.9578 108893.3002 81313.2754 31068.2382 -of GTiff D:/SRTM_PT_25m.tif C:/Users/PedroVenancio/AppData/Local/Temp/processing_PlqxDO/caaf47333c4e4516abbe642839e8c07e/OUTPUT.tif
GDAL command output:
Input file size is 11360, 23200
0...10...20...30...40...50...60...70...80...90...100 - done.
Process completed successfully
0...10...20...30...40...50D:\src\osgeo4w\src\qgis-dev\qgis\src\core\providers\ogr\qgsogrprovider.cpp(4880) : (QgsOgrProvider::open) [283ms] OGR failed to opened in update mode, trying in read-only mode
D:\src\osgeo4w\src\qgis-dev\qgis\src\core\qgsmessagelog.cpp(29) : (QgsMessageLog::logMessage) [7ms] 2021-02-18T18:31:18 OGR[1] Cannot open C:/Users/PedroVenancio/AppData/Local/Temp/processing_PlqxDO/caaf47333c4e4516abbe642839e8c07e/OUTPUT.tif.()
D:\src\osgeo4w\src\qgis-dev\qgis\src\core\qgsmessagelog.cpp(29) : (QgsMessageLog::logMessage) [53ms] 2021-02-18T18:31:18 OpenCL[1] Found OpenCL library filename C:\WINDOWS\SYSTEM32\OpenCL.dll
D:\src\osgeo4w\src\qgis-dev\qgis\src\core\qgsmessagelog.cpp(29) : (QgsMessageLog::logMessage) [9ms] 2021-02-18T18:31:18 OpenCL[1] OpenCL Product version: 2.2.8.0
D:\src\osgeo4w\src\qgis-dev\qgis\src\core\qgsopenclutils.cpp(159) : (QgsOpenClUtils::init::<lambda_86299811fd53d075b9f19e614e21366f>::operator ()) [7ms] d:Comments subBlock:\StringFileInfo\040904e4\Comments
D:\src\osgeo4w\src\qgis-dev\qgis\src\core\qgsopenclutils.cpp(159) : (QgsOpenClUtils::init::<lambda_86299811fd53d075b9f19e614e21366f>::operator ()) [8ms] d:InternalName subBlock:\StringFileInfo\040904e4\InternalName
D:\src\osgeo4w\src\qgis-dev\qgis\src\core\qgsmessagelog.cpp(29) : (QgsMessageLog::logMessage) [9ms] 2021-02-18T18:31:18 OpenCL[1] Found OpenCL version info InternalName: OpenCL
D:\src\osgeo4w\src\qgis-dev\qgis\src\core\qgsopenclutils.cpp(159) : (QgsOpenClUtils::init::<lambda_86299811fd53d075b9f19e614e21366f>::operator ()) [6ms] d:ProductName subBlock:\StringFileInfo\040904e4\ProductName
D:\src\osgeo4w\src\qgis-dev\qgis\src\core\qgsmessagelog.cpp(29) : (QgsMessageLog::logMessage) [8ms] 2021-02-18T18:31:18 OpenCL[1] Found OpenCL version info ProductName: Khronos OpenCL ICD Loader
D:\src\osgeo4w\src\qgis-dev\qgis\src\core\qgsopenclutils.cpp(159) : (QgsOpenClUtils::init::<lambda_86299811fd53d075b9f19e614e21366f>::operator ()) [8ms] d:CompanyName subBlock:\StringFileInfo\040904e4\CompanyName
D:\src\osgeo4w\src\qgis-dev\qgis\src\core\qgsmessagelog.cpp(29) : (QgsMessageLog::logMessage) [8ms] 2021-02-18T18:31:18 OpenCL[1] Found OpenCL version info CompanyName: Khronos Group
D:\src\osgeo4w\src\qgis-dev\qgis\src\core\qgsopenclutils.cpp(159) : (QgsOpenClUtils::init::<lambda_86299811fd53d075b9f19e614e21366f>::operator ()) [6ms] d:LegalCopyright subBlock:\StringFileInfo\040904e4\LegalCopyright
D:\src\osgeo4w\src\qgis-dev\qgis\src\core\qgsmessagelog.cpp(29) : (QgsMessageLog::logMessage) [9ms] 2021-02-18T18:31:19 OpenCL[1] Found OpenCL version info LegalCopyright: Copyright © The Khronos Group Inc 2016-2020
D:\src\osgeo4w\src\qgis-dev\qgis\src\core\qgsopenclutils.cpp(159) : (QgsOpenClUtils::init::<lambda_86299811fd53d075b9f19e614e21366f>::operator ()) [8ms] d:ProductVersion subBlock:\StringFileInfo\040904e4\ProductVersion
D:\src\osgeo4w\src\qgis-dev\qgis\src\core\qgsopenclutils.cpp(159) : (QgsOpenClUtils::init::<lambda_86299811fd53d075b9f19e614e21366f>::operator ()) [8ms] d:FileDescription subBlock:\StringFileInfo\040904e4\FileDescription
D:\src\osgeo4w\src\qgis-dev\qgis\src\core\qgsmessagelog.cpp(29) : (QgsMessageLog::logMessage) [9ms] 2021-02-18T18:31:19 OpenCL[1] Found OpenCL version info FileDescription: OpenCL Client DLL
D:\src\osgeo4w\src\qgis-dev\qgis\src\core\qgsopenclutils.cpp(159) : (QgsOpenClUtils::init::<lambda_86299811fd53d075b9f19e614e21366f>::operator ()) [9ms] d:LegalTrademarks subBlock:\StringFileInfo\040904e4\LegalTrademarks
D:\src\osgeo4w\src\qgis-dev\qgis\src\core\qgsopenclutils.cpp(159) : (QgsOpenClUtils::init::<lambda_86299811fd53d075b9f19e614e21366f>::operator ()) [9ms] d:PrivateBuild subBlock:\StringFileInfo\040904e4\PrivateBuild
D:\src\osgeo4w\src\qgis-dev\qgis\src\core\qgsopenclutils.cpp(159) : (QgsOpenClUtils::init::<lambda_86299811fd53d075b9f19e614e21366f>::operator ()) [8ms] d:FileVersion subBlock:\StringFileInfo\040904e4\FileVersion
D:\src\osgeo4w\src\qgis-dev\qgis\src\core\qgsmessagelog.cpp(29) : (QgsMessageLog::logMessage) [8ms] 2021-02-18T18:31:19 OpenCL[1] Found OpenCL version info FileVersion: 2.2.8.0
D:\src\osgeo4w\src\qgis-dev\qgis\src\core\qgsopenclutils.cpp(159) : (QgsOpenClUtils::init::<lambda_86299811fd53d075b9f19e614e21366f>::operator ()) [8ms] d:OriginalFilename subBlock:\StringFileInfo\040904e4\OriginalFilename
D:\src\osgeo4w\src\qgis-dev\qgis\src\core\qgsmessagelog.cpp(29) : (QgsMessageLog::logMessage) [7ms] 2021-02-18T18:31:19 OpenCL[1] Found OpenCL version info OriginalFilename: OpenCL.dll
D:\src\osgeo4w\src\qgis-dev\qgis\src\core\qgsopenclutils.cpp(159) : (QgsOpenClUtils::init::<lambda_86299811fd53d075b9f19e614e21366f>::operator ()) [7ms] d:SpecialBuild subBlock:\StringFileInfo\040904e4\SpecialBuild
D:\src\osgeo4w\src\qgis-dev\qgis\src\core\qgsmessagelog.cpp(29) : (QgsMessageLog::logMessage) [437ms] 2021-02-18T18:31:19 OpenCL[1] Could not load OpenCL program from path /hillshade.cl.
D:\src\osgeo4w\src\qgis-dev\qgis\src\core\qgsmessagelog.cpp(29) : (QgsMessageLog::logMessage) [14ms] 2021-02-18T18:31:19 OpenCL[2] Error loading OpenCL program sources
Error loading OpenCL program sources
D:\src\osgeo4w\src\qgis-dev\qgis\src\core\qgsmessagelog.cpp(29) : (QgsMessageLog::logMessage) [13ms] 2021-02-18T18:31:19 Processing[2] Error loading OpenCL program sources
Error loading OpenCL program sources
ERROR:  Error loading OpenCL program sources
D:\src\osgeo4w\src\qgis-dev\qgis\src\core\qgsmessagelog.cpp(29) : (QgsMessageLog::logMessage) [13ms] 2021-02-18T18:31:19 Processing[2] Error encountered while running Hillshade
Error encountered while running Hillshade
ERROR:  Error encountered while running Hillshade
```

Running Clip Raster by Mask Layer and Clip Raster by Extent directly from Processing, they work as expected.

**Comment by roya0045** [comment]
Why is `QgsLayoutItemScaleBar` in the trace??

**Comment by PedroVenancio** [comment]
The crash also happens on Linux (Ububtu 20.04), so the title needs to be changed. @gioman can you change please?

**Comment by gioman** [comment]
Done.

**Comment by PedroVenancio** [comment]
@nyalldawson 

It seems that are other GDAL algorithms giving problems inside models.

Can you please take a look at this new version of the model, that adds the gdal_calc algorithm:

[Hillshade.zip](https://github.com/qgis/QGIS/files/6014700/Hillshade.zip)

QGIS just freezes.

**Comment by nyalldawson** [comment]
@PedroVenancio does gdal_calc work from a command line for you? I could only reproduce this when gdal_calc was not installed

**Comment by PedroVenancio** [comment]
Hi @nyalldawson 

Yes, gdalcalc.py is available inside `..\OSGeo4W64\apps\qgis-dev\python\plugins\processing\algs\gdal (new OSGeo4W installer)`.

However, I can not use it from command line. I always get

```
No calculation provided. Nothing to do!
Usage: gdal_calc.py --calc=expression --outfile=out_filename [-A filename]
                    [--A_band=n] [-B...-Z filename] [other_options]

Options:
  -h, --help            show this help message and exit
  --calc=expression     calculation in gdalnumeric syntax using +-/* or any
                        numpy array functions (i.e. log10()). May appear
                        multiple times to produce a multi-band file
  -A filename           input gdal raster file, you can use any letter (A-Z)
  --A_band=n            number of raster band for file A (default 1)
  --outfile=filename    output file to generate or fill
  --NoDataValue=value   output nodata value (default datatype specific value)
  --type=datatype       output datatype, must be one of ['Byte', 'UInt16',
                        'Int16', 'UInt32', 'Int32', 'Float32', 'Float64']
  --format=gdal_format  GDAL format for output file
  --creation-option=option, --co=option
                        Passes a creation option to the output format driver.
                        Multiple options may be listed. See format specific
                        documentation for legal creation options for each
                        format.
  --allBands=[A-Z]      process all bands of given raster (A-Z)
  --overwrite           overwrite output file if it already exists
  --debug               print debugging information
  --quiet               suppress progress messages
  --optfile=optfile     Read the named file and substitute the contents into
                        the command line options list.
```

In QGIS 3.16 I do 

C:\>py3_env

to set Python3 environment and then run gdal_calc, and it works as expected.

With new OSGeo4W installer, 

```
C:\OSGeo4W64>py3_env
'py3_env' is not recognized as an internal or external command,
operable program or batch file.
```

So the problem seems to be in setting Python3 environment to gdal_calc.py run.

@jef-n Do you know what can be happening?

**Comment by gioman** [comment]
@PedroVenancio @nyalldawson @jef-n 

Just had try again to the new osgeo4w installer on a clean Win10 machine

*) no python GDAL tool works, not even from the osgeo4w command line, the error is always like

` No module named gdal_calc` or  `No module named gdal_fillnull`, etc.

*) if the osgeo4w is not run as administrator it won't create the "osgeo" group and shortcuts in the start menu

*) after having installed qgis, on the first start QGIS remain stuck at the splashscreen, then crashes. Running it again is ok

*) after the above I restarted the system, and then trying launch QGIS I was greeted by

![Screenshot_20210220_195904](https://user-images.githubusercontent.com/1951107/108608142-f9631c00-73bc-11eb-932b-262ec2087cdf.png)

*) I then re-installed everything and QGIS started ok again

*) as far I have understand now we can only ship SAGA 7.8 (because of Proj) and the description files are pulled from the SAGA project (which creates them) https://github.com/qgis/QGIS/issues/41649#issuecomment-782023462 so I think that the message "SAGA version 7.8.2 is not officially supported - algorithms may encounter issues" that shows opening any SAGA tool should be removed

*) SAGA and GRASS tools seems to work ok


I'm reporting this issues here as I'm not sure what is the right place for this new osgeo4w installer.

**Comment by gioman** [comment]
I forgot another issue:

*) the shortcut created in the desktop to the osgeo4w shell does not open it, it just open a Windows explorer window



> C:>py3_env
> 
> to set Python3 environment

A question, why is this necessary now? If I'm not wrong this was not necessary in the past (i.e. 2.*).

**Comment by jef-n** [comment]
* The latest installer doesn't enable "all users" shortcuts, if the installer is not running elevated
* the default/only python in rebooted osgeo4w is 3.  There's no need for py3_env.
* I don't know if there are processing issues with SAGA 7.  I guess the warning was introduced for a reason and that might still apply.
* gdal batch file creation for python scripts was fixed (jef-n/OSGeo4W@f4effdf3649109be11ea1233af59694cf167b42b)

**Comment by PedroVenancio** [comment]
> gdal batch file creation for python scripts was fixed ([jef-n/OSGeo4W@f4effdf](https://github.com/jef-n/OSGeo4W/commit/f4effdf3649109be11ea1233af59694cf167b42b))

Thanks @jef-n it's fixed on OSGeo4W shell.

It still fails on QGIS, but I believe it will be fixed in the next nightly.

Another thing I see is that qgis-ltr.bat does not have the correspondent qgis-ltr-grass.bat.

**Comment by jef-n** [comment]
> It still fails on QGIS, but I believe it will be fixed in the next nightly.

There are no testing nightlies.

> Another thing I see is that qgis-ltr.bat does not have the correspondent qgis-ltr-grass.bat.

qgis-ltr-grass.bat is in the qgis-ltr-grass-plugin package.

**Comment by PedroVenancio** [comment]
> There are no testing nightlies.

So gdal_calc and other GDAL python scripts should work now?

**Comment by jef-n** [comment]
> So gdal_calc and other GDAL python scripts should work now?

yes, but you just said that the don't!?

**Comment by PedroVenancio** [comment]
> > So gdal_calc and other GDAL python scripts should work now?
> 
> yes, but you just said that the don't!?

That's correct @jef-n, even reinstalling QGIS it doesn't work. Works fine in command line.

**Comment by jef-n** [comment]
> That's correct @jef-n, even reinstalling QGIS it doesn't work. Works fine in command line.

Are you referring to a GDAL issue or to that QGIS issue Nyall fixed?

**Comment by PedroVenancio** [comment]
> 
> Are you referring to a GDAL issue or to that QGIS issue Nyall fixed?

I think the Nyall's fix is just to do not freeze QGIS when the algorithm does not work, isn't it? I thought the problem was in the fact that the GDAL python script won't run on OSGeo4W, because it does not happen on Linux.

**Comment by jef-n** [comment]
> There are no testing nightlies.

qgis-dev built and qgis-rel-dev triggered.

**Comment by PedroVenancio** [comment]
> qgis-dev built and qgis-rel-dev triggered.

@jef-n tested qgis-dev and got

```
QGIS version: 3.19.0-Master
QGIS code revision: 03eaf9f29
Qt version: 5.15.2
GDAL version: 3.2.1
GEOS version: 3.9.1-CAPI-1.14.2
PROJ version: Rel. 7.2.1, January 1st, 2021
PDAL version: 2.2.0 (git-version: 38aa11)
Processing algorithm…
Algorithm 'Raster calculator' starting…
Input parameters:
{ 'BAND_A' : 1, 'BAND_B' : None, 'BAND_C' : None, 'BAND_D' : None, 'BAND_E' : None, 'BAND_F' : None, 'EXTRA' : '', 'FORMULA' : 'A*2', 'INPUT_A' : 'D:/Temp/processing_pgUNVN/19a4d29a4bc74b2eb1dea9ca2db5785e/OUTPUT.tif', 'INPUT_B' : None, 'INPUT_C' : None, 'INPUT_D' : None, 'INPUT_E' : None, 'INPUT_F' : None, 'NO_DATA' : None, 'OPTIONS' : '', 'OUTPUT' : 'TEMPORARY_OUTPUT', 'RTYPE' : 5 }

GDAL command:
gdal_calc --calc "A*2" --format GTiff --type Float32 -A D:/Temp/processing_pgUNVN/19a4d29a4bc74b2eb1dea9ca2db5785e/OUTPUT.tif --A_band 1 --outfile D:/Temp/processing_pgUNVN/58176b4a593c442bbeb78878e3f330f3/OUTPUT.tif
GDAL command output:
Process gdal_calc failed to start. Either gdal_calc is missing, or you may have insufficient permissions to run the program.
Execution failed after 0.15 seconds

Loading resulting layers
Algorithm 'Raster calculator' finished
```

**Comment by jef-n** [comment]
should be fixed in 570972b227075335f2b4a6ca2d5e6cb00330a0f6 (qgis* builds triggered)

**Comment by gioman** [comment]
> The latest installer doesn't enable "all users" shortcuts, if the installer is not running elevated

@jef-n I guess we should document this(?) as it is a change compared to the "old" ogseo4w.



> I don't know if there are processing issues with SAGA 7. I guess the warning was introduced for a reason and that might still apply.

no, the warning was added because the description files were for 2.*, so if someone had installed 7.* could have found broken tools because maybe the tool parameters had changed. Now we ship SAGA 7.* with appropriate description files, so the warning can go.

**Comment by PedroVenancio** [comment]
> 
> 
> should be fixed in [570972b](https://github.com/qgis/QGIS/commit/570972b227075335f2b4a6ca2d5e6cb00330a0f6) (qgis* builds triggered)

Fix confirmed @jef-n ! Thank you very much!!
