### ISSUE TITLE
Wrong histogram plot if raster data type is byte

### ISSUE THREAD

**Issue by andremano** [qgis/QGIS#45379]
### What is the bug or the crash?

If a raster is of type byte, the histogram plot appears to be incorrect. Below the histogram calculated over a byte data type (incorrect):
![image](https://user-images.githubusercontent.com/6665872/135857957-eefef09d-1b15-4cd8-bbbe-6eec5d08100d.png)

If we export the raster into float32 then we get the correct histogram:
![image](https://user-images.githubusercontent.com/6665872/135858089-0529a892-3bbc-4863-a65f-5b905f80287f.png)

### Steps to reproduce the issue

Use [this dataset](https://drive.google.com/file/d/11upBikOC6Uzgkx0PUWixr_Ffky6fOkmE/view?usp=sharing) an calculate histogram over band 4 (example depicted above) over the **tm24aug99_sub** raster (byte) and comparre it with histogram obrained from **tm24aug99_REFORGED** (float32). 

### Versions

QGIS version
3.16.11-Hannover
QGIS code revision
26cc1c76
Compiled against Qt
5.15.2
Running against Qt
5.15.2
Compiled against GDAL/OGR
3.3.1
Running against GDAL/OGR
3.3.1
Compiled against GEOS
3.9.1-CAPI-1.14.2
Running against GEOS
3.9.1-CAPI-1.14.2
Compiled against SQLite
3.35.2
Running against SQLite
3.35.2
PostgreSQL Client Version
13.0
SpatiaLite Version
5.0.1
QWT Version
6.1.3
QScintilla2 Version
2.11.5
Compiled against PROJ
8.1.1
Running against PROJ
Rel. 8.1.1, September 1st, 2021
OS Version
Windows 10 Version 2009
Active python plugins
csv_tools; 
pg_raster_import; 
quick_map_services; 
db_manager; 
MetaSearch; 
processing

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

In QGIS 3.10 this did not occur. Issue occurs since 3.16.1 and continues into 3.16.11.

**Comment by gioman** [comment]
@andremano duplicate of https://github.com/qgis/QGIS/issues/44927 ?

**Comment by elpaso** [comment]
I have the feeling that this was fixed in master, can you please check?

**Comment by andremano** [comment]
> @andremano duplicate of #44927 ?

It appears so.

**Comment by andremano** [comment]
> I have the feeling that this was fixed in master, can you please check?

sure

**Comment by andremano** [comment]
> I have the feeling that this was fixed in master, can you please check?

Issue remains. See below the test environment:

QGIS version 3.21.0-Master
QGIS code revision de53894dab

**Comment by gioman** [comment]
> Issue remains. See below the test environment:
> 
> QGIS version 3.21.0-Master QGIS code revision [de53894](https://github.com/qgis/QGIS/commit/de53894dabf633f1a50dedfd50155ac81111a673)

@andremano please also leave this comment in the other ticket.

**Comment by andremano** [comment]
just re-opening this issue - i accidentely closed it
