### ISSUE TITLE
All vertex editing eventually stops working (+Crash Report as that often happens after this error)

### ISSUE THREAD

**Issue by PhiliusMaximus** [qgis/QGIS#48028]
## User Feedback

The issue is that when I'm creating or editing a feature the vertex I click is not the vertex that is selected: I click on a vertex and the 'ghost line' (the lines that shows where your new feature will be/how it will look) jumps to another vertex, usually to a different but nearby feature. Once this happens, I have found no method of reseting other than to close and re-open QGIS.

This occurs with lines and polygons on .shp files.

I have noted that this occurs when creating new features, adding parts, and adding rings. 

It sometimes crashes when I close, so I have attached a crash report in case that is useful.

I have tried with different user profiles, including ones with no plugins installed, and this does not make any difference.

My project CRS and layer CRS are both set to the same 

This has been going on for some time, but it feels like it's happening more frequently as I've been updating versions.

## Report Details

**Crash ID**: [940da8b284a337381d7ed4d5c81af46c33039af2](https://github.com/qgis/QGIS/search?q=940da8b284a337381d7ed4d5c81af46c33039af2&type=Issues)

**Stack Trace**
<pre>
QMimeType::staticMetaObject :
QgsMapCanvas::cancelJobs :
QgsMapCanvas::~QgsMapCanvas :
QgsPluginRegistry::operator= :
QgisApp::~QgisApp :
QgsPluginRegistry::operator= :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.22.4-Bia?owie?a
QGIS code revision: ce8e65e9
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.4.1
Running against GDAL: 3.4.1

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19043

### Steps to reproduce the issue

I have attached the QGIS project I am using and two .shp files that contain some sample data. They have both been producing the errors and contain data that have been producing the errors.
There are other layers referenced int he QGIS project but either I don't think they're relevant or I can't share them. If you do need them, maybe I can take the data out?

To replicate the issue, please use various methods of creating and editing a the two layers for 15 or so minutes. If I edit/create data for long enough, it always happens.

[Sample Data.zip](https://github.com/qgis/QGIS/files/8379731/Sample.Data.zip)

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.22.4-Białowieża | QGIS code revision | ce8e65e9
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.5
GDAL/OGR version | 3.4.1
PROJ version | 8.2.1
EPSG Registry database version | v10.041 (2021-12-03)
GEOS version | 3.10.2-CAPI-1.16.0
SQLite version | 3.37.2
PDAL version | 2.3.0
PostgreSQL client version | 13.0
SpatiaLite version | 5.0.1
QWT version | 6.1.3
QScintilla2 version | 2.11.5
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.5
processing | 2.12.99
sagaprovider | 2.12.99

</body></html>QGIS version
3.22.4-Białowieża
QGIS code revision
[ce8e65e9](https://github.com/qgis/QGIS/commit/ce8e65e9)
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.4.1
PROJ version
8.2.1
EPSG Registry database version
v10.041 (2021-12-03)
GEOS version
3.10.2-CAPI-1.16.0
SQLite version
3.37.2
PDAL version
2.3.0
PostgreSQL client version
13.0
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows 10 Version 2009

Active Python plugins
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.5
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by nyalldawson** [comment]
The crash is fixed by https://github.com/qgis/QGIS/pull/48591

**Comment by YiyuWYY** [comment]
I have the same problem with you. Sometimes it's the ghost lines but sometimes there is even nothing. I also tried the newest version but it's even worse. 
Here is my question.
https://github.com/qgis/QGIS/issues/49237#issue-1293133515

**Comment by YiyuWYY** [comment]
@uclaros No i am the only one who do this.

**Comment by NelsonW13** [comment]
I guess, I have the same problem. I posted it on stackexchange: https://gis.stackexchange.com/questions/441528/qgis-3-22-add-new-memory-layer-vertextool-bug-pyqgis . There is PyQGIS-code to create a simple function that reproduce the problem and showing the result of the issue as gif. Is that the same issue for you?

**Comment by PhiliusMaximus** [comment]
@NelsonW13 that is how my issue appears, yes, but I found that some lines on my shapefile were getting mixed up with other lines - not with blank space as it appears in your animation.

I have also recently noted that the issue is much less common when I have line data stored on an MSSQL database, although it still occurs.
