### ISSUE TITLE
No module named 'qgslayoutchecker' using docker "qgis/qgis:latest"

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS#53051]
### What is the bug or the crash?

For almost two weeks, when running tests (for QGIS-Documentation, but it was reported in [dev list](https://lists.osgeo.org/pipermail/qgis-developer/2023-May/065785.html) that we are not alone), they always fail and report
> Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python3.10/doctest.py", line 1350, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest composer (setup code)[0]>", line 22, in <module>
        from qgis.testing import start_app
      File "/usr/lib/python3/dist-packages/qgis/testing/__init__.py", line 56, in <module>
        from qgslayoutchecker import QgsLayoutChecker
    ModuleNotFoundError: No module named 'qgslayoutchecker'

Afaics, that module is nowhere used in the docs. Same doctest codes pass without issue on 3.28.
Thanks for fixing.

### Steps to reproduce the issue

dunno maybe running the doctest? But you can see the outputs at (pick anything) https://github.com/qgis/QGIS-Documentation/actions/workflows/doctest.yml?query=branch%3Amaster

### Versions

master 3.31

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by nicogodet** [comment]
Faulty commit https://github.com/qgis/QGIS/commit/3492ddbcfa67a97ca1175f80326b3701d819fb55

`from qgslayoutchecker import QgsLayoutChecker` was a relative import before
Solution would be to port QgsLayoutChecker to c++ 
Or easy fix move `qgis/QGIS/tree/master/tests/src/python/qgslayoutchecker.py` to `qgis/QGIS/tree/master/python/testing/` (and fix cmakelist) and use `from qgis.testing.qgslayoutchecker import QgsLayoutChecker`

**Comment by m-kuhn** [comment]
Fix inbound

https://github.com/qgis/QGIS/compare/master...m-kuhn:QGIS:intsall_qgslayoutchecker

**Comment by DelazJ** [comment]
@m-kuhn your [diff](https://github.com/qgis/QGIS/compare/master...m-kuhn:QGIS:intsall_qgslayoutchecker#diff-dbb55b6871a9157f22dc7a979009676cb03f2fadefc557ad0e66a47c92a93503R56) looks buggy to me

**Comment by DelazJ** [comment]
And thanks for the fix

**Comment by m-kuhn** [comment]
fixed, thanks for spotting

**Comment by nyalldawson** [comment]
@m-kuhn the python layout checker class is a 1:1 copy of the QgsLayoutChecker class from core. I don't see any reason to keep the python class around...

**Comment by DelazJ** [comment]
@m-kuhn Thanks for the fix.
Unfortunately, it does not seem enough. A couple of the [docker image](https://github.com/qgis/pyqgis/actions/runs/4976155614) updates occurred in the meantime but [doctest is still failing](https://github.com/qgis/QGIS-Documentation/actions/workflows/doctest.yml), due to QgsLayoutChecker. Only line number changed in the report (if ever it matters)
> Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python3.10/doctest.py", line 1350, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest composer (setup code)[0]>", line 22, in <module>
        from qgis.testing import start_app
      File "/usr/lib/python3/dist-packages/qgis/testing/__init__.py", line 45, in <module>
        from qgis.core import (
    ImportError: cannot import name 'QgsLayoutChecker' from 'qgis.core' (/usr/lib/python3/dist-packages/qgis/core/__init__.py)

**Comment by DelazJ** [comment]
Fixed by #53328
