### ISSUE TITLE
Remove connection does not delete the connection

### ISSUE THREAD

**Issue by frspp** [qgis/QGIS#53321]
### What is the bug or the crash?

Bug

### Steps to reproduce the issue

1. Open Browser
2. Open WMS/WMTS list
3. Right click a connection, choose "remove connection"
4. Connection does not get deleted

Have this bug with all connections.

### Versions

3.30.2, Windows 11

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by agiudiceandrea** [comment]
@3nids, it seems this issue is the same as https://github.com/qgis/QGIS/issues/52275 which should have been allegedly fixed by you with https://github.com/qgis/QGIS/pull/52282 and https://github.com/qgis/QGIS/pull/52725.

**Comment by agiudiceandrea** [comment]
@frspp, are you sure? It seems to me the issue does occur also with QGIS 3.30.3.

**Comment by frasemcl** [comment]
I am unable to remove an 'ArcGIS REST Servers' connection by right clicking on the connection and choosing 'Remove Connection...' in QGIS 3.30.3. Seems as though nothing happens and I can't find another way to remove it. I suspect this is related. Let me know if more info would be helpful.

**Comment by andrewrfrench** [comment]
In 3.32 I am unable to delete an ArcGIS Rest Server with right click and Remove. Nothing happens.

**Comment by GuidoS** [comment]
> In 3.32 I am unable to delete an ArcGIS Rest Server with right click and Remove. Nothing happens.

Still an issue in 3.32.2-Lima. I am using [this service](https://gis.dep.pa.gov/depgisprd/rest/services/OilGas/OilGasAllStrayGasEGSP/MapServer).

Is there anything I can do to help resolve this?

**Comment by agiudiceandrea** [comment]
@3nids, it seems the issue is not yet fixed.

**Comment by IspookGt** [comment]
looks like op has the same problems as i do, only difference being that its on WMS, seems like its a bug from the app itself, As for the new configs/connections... i have no idea whats wrong with it, i also tried delete->reinstalling, didnt work unfortunately :/

**Comment by winchop** [comment]
3.34.0-Prizren still got this bug

**Comment by agiudiceandrea** [comment]
@winchop, thanks for reporting. Could you please give more info on your system and the situation in which the issue occurs?

**Comment by pathmapper** [comment]
There are still issues removing the connections in `master` (new profile, details below).

Just tried it for `WMS` / `WFS` / `XYZ Tiles` and `ArcGIS REST Servers` connections and removed connections are still present after a restart of QGIS. 

Only if the connection is immediately deleted a second time, it is not present after another restart of QGIS:<br>
remove connection -> close/open QGIS - remove connection -> close/open QGIS 


This is not true for `XYZ Tiles` where only the URL of the connection is deleted after this procedure (not the connection itself).



QGIS version | 3.35.0-Master | QGIS code revision | 461a3158d01
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.10.12
GDAL/OGR version | 3.8.0dev-dd53b90c10
PROJ version | 8.2.1
EPSG Registry database version | v10.041 (2021-12-03)
GEOS version | 3.10.2-CAPI-1.16.0
SQLite version | 3.37.2
PDAL version | 2.3.0
PostgreSQL client version | 14.9 (Ubuntu 14.9-0ubuntu0.22.04.1)
SpatiaLite version | 5.0.1
QWT version | 6.1.4
QScintilla2 version | 2.11.6
OS version | Ubuntu 22.04.3 LTS
  |   |   |  
Active Python plugins
grassprovider | 2.12.99
MetaSearch | 0.3.6
processing | 2.12.99
db_manager | 0.1.20

**Comment by winchop** [comment]
> @winchop, thanks for reporting. Could you please give more info on your system and the situation in which the issue occurs?

      from the data source manager or the browser panel , drop down the XYZ Tiles ,pick one connection AABB eg ,right click , chose remove connection AABB ,this connection will do disappear ,but when I close Qgis then restart ,the connection AABB will come back when I drop down the XYZ Tiles, edit it, name is still there URL is empty. It's not a big problem ,but my drop down list is too much to find. 
I find a way to fix ,create a new account , import the connections carefully.but still I can't remove.

some info maybe help:

QGIS version | 3.34.2-Prizren | QGIS code revision | 7d199797fc
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.9.5
GDAL/OGR version | 3.8.2
PROJ version | 9.3.1
EPSG Registry database version | v10.098 (2023-11-24)
GEOS version | 3.12.1-CAPI-1.18.1
SQLite version | 3.41.1
PDAL version | 2.6.0
PostgreSQL client version | 15.2
SpatiaLite version | 5.1.0
QWT version | 6.1.6
QScintilla2 version | 2.13.4
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
AnotherDXF2Shape | 1.3.1
ArcheoCAD | 3.2.2
Beeline | 0.2.0
CalculateGeometry | 0.6.9
cartography_tools | 1.2.1
CivilEng | 0.2
color_attribute | 0.2.1
DataPlotly | 4.1.0
deepness | 0.5.4
deg_2_dms | 0.3
DissolveWithStats | 0.6
DWG2DXF | 0.1
excel_sync | 3.6
FragScape | 2.0.6
geohey_toolbox | 0.4.2
geometric_attributes | 0.4
GeometryShapes | 0.7
GroupStats | 2.2.7
ImportPhotos | 3.0.5
layout_panel-main | 0.3
lftools | 1.12.5
MagicWand-master | 1.3.2
mapswipetool_plugin | 1.2
monokai | 1.0
monokaiprospectrum | 1.0
numerator | 0.5
opacity_set_01 | 0.2
OpenTopography-DEM-Downloader | 2.0
ORStools | 1.7.0
pluginbuilder3 | 3.2.1
plugin_reloader | 0.9.3
processing_saga_nextgen | 1.0.0
profiletool | 4.2.6
qgeric | 1.91
qgis-maptiler-plugin | 3.2
Qgis2threejs | 2.7.1
QGISSortAndNumber-master | 1.0
qProf | 0.5.1
qqpoi | 0.1
QuickMultiAttributeEdit3 | version 3.0.3
QWater | 3.1.8
reloader | 0.1
rvt-qgis | 0.9.6
open_lidar_tools | 2.2.2
shapefile_encoding_fixer | 0.7.1
smooth_geometry | 1.1.1
spline | 0.2
table2style | 2.1
terminus_processing | 1.0.2
TerrainShading | 0.9.3
tianditu-tools | 0.3.1
VectorMCDA | 3.0.1
volume_calculation_tool | 0.4
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.6
otbprovider | 2.12.99
processing | 2.12.99

</body></html>QGIS version
3.34.2-Prizren
QGIS code revision
[7d199797fc](https://github.com/qgis/QGIS/commit/7d199797fc)
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.8.2
PROJ version
9.3.1
EPSG Registry database version
v10.098 (2023-11-24)
GEOS version
3.12.1-CAPI-1.18.1
SQLite version
3.41.1
PDAL version
2.6.0
PostgreSQL client version
15.2
SpatiaLite version
5.1.0
QWT version
6.1.6
QScintilla2 version
2.13.4
OS version
Windows 11 




Active Python plugins
AnotherDXF2Shape
1.3.1
ArcheoCAD
3.2.2
Beeline
0.2.0
CalculateGeometry
0.6.9
cartography_tools
1.2.1
CivilEng
0.2
color_attribute
0.2.1
DataPlotly
4.1.0
deepness
0.5.4
deg_2_dms
0.3
DissolveWithStats
0.6
DWG2DXF
0.1
excel_sync
3.6
FragScape
2.0.6
geohey_toolbox
0.4.2
geometric_attributes
0.4
GeometryShapes
0.7
GroupStats
2.2.7
ImportPhotos
3.0.5
layout_panel-main
0.3
lftools
1.12.5
MagicWand-master
1.3.2
mapswipetool_plugin
1.2
monokai
1.0
monokaiprospectrum
1.0
numerator
0.5
opacity_set_01
0.2
OpenTopography-DEM-Downloader
2.0
ORStools
1.7.0
pluginbuilder3
3.2.1
plugin_reloader
0.9.3
processing_saga_nextgen
1.0.0
profiletool
4.2.6
qgeric
1.91
qgis-maptiler-plugin
3.2
Qgis2threejs
2.7.1
QGISSortAndNumber-master
1.0
qProf
0.5.1
qqpoi
0.1
QuickMultiAttributeEdit3
version 3.0.3
QWater
3.1.8
reloader
0.1
rvt-qgis
0.9.6
open_lidar_tools
2.2.2
shapefile_encoding_fixer
0.7.1
smooth_geometry
1.1.1
spline
0.2
table2style
2.1
terminus_processing
1.0.2
TerrainShading
0.9.3
tianditu-tools
0.3.1
VectorMCDA
3.0.1
volume_calculation_tool
0.4
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
otbprovider
2.12.99
processing
2.12.99











> @winchop, thanks for reporting. Could you please give more info on your system and the situation in which the issue occurs?

**Comment by agiudiceandrea** [comment]
Hi @3nids , any news on this issue?

**Comment by agiudiceandrea** [comment]
Hi @3nids , any news on this issue? See another recent issue report https://github.com/qgis/QGIS/issues/56506.

**Comment by sayers67** [comment]
Still an issue for WMS/WFS in 3.36.0-Maidenhead, Qt version 5.15.3, Python version, 3.9.18, GDAL/OGR version 3.8.4

**Comment by fgcarto** [comment]
Still had this issue with 3.38.2. I had to open and manually edit the QGIS3.ini to remove all mentions of the unwanted XYZ Tiles services (i manually added a prefix to their names to find them).


Version de QGIS
3.38.2-Grenoble
Révision du code
130c432394
Version de Qt
5.15.13
Version de Python
3.12.5
Version de GDAL/OGR
3.9.2
Version de Proj
9.4.0
Version de la base de données du registre EPSG
v11.004 (2024-02-24)
Version de GEOS
3.12.2-CAPI-1.18.2
Version de SQLite
3.45.1
Version de PDAL
2.6.3
Version du client PostgreSQL
16.2
Version de SpatiaLite
5.1.0
Version de QWT
6.2.0
Version de QScintilla2
2.14.1
Version de l'OS
Windows 10 Version 2009




Extensions Python actives
AzureMapsCreator
1.0.1
GTFS_Loader
1.0.0
networks
2.7.22
ORStools
1.8.4
pg_metadata
1.3.1
qgis-py-plugin
0.1
QNEAT3
1.0.5
quick_map_services
0.19.34
replace_geometry
2.0
StreetView
3.2
db_manager
0.1.20
MetaSearch
0.3.6
processing
2.12.99

**Comment by nyalldawson** [comment]
@fgcarto 3.38.2 is outdated, please retest with 3.38.3

**Comment by fgcarto** [comment]
I'll try. It's a corporate environment and it could takes weeks.

**Comment by 3nids** [comment]
@fgcarto 3.38.2 was released after the fix. Could you share the content of the ini file? or the XYZ section?
