### ISSUE TITLE
Wrong rendering for `HIGHLIGHT_LABEL_ROTATION` above 89°

### ISSUE THREAD

**Issue by nboisteault** [qgis/QGIS#54598]
### What is the bug or the crash?

When doing a `GetPrint` request with the `HIGHLIGHT_LABEL_ROTATION` parameter above 89° the rendering is wrong.

- 89°:

![print_print_labels](https://github.com/qgis/QGIS/assets/2145040/d2f251c3-2a69-4a41-9cda-42aaaed059dd)

- 90°, the rotation is now anti clockwise:

![print_print_labels(1)](https://github.com/qgis/QGIS/assets/2145040/3a80c7bc-f605-478d-bd18-6cbb2486ae34)

- 180°, the label should be upside down but is not:

![print_print_labels(2)](https://github.com/qgis/QGIS/assets/2145040/3b2f3fa9-620c-436c-8881-ecd134be750c)

### Steps to reproduce the issue

Do `GetPrint` request with the `HIGHLIGHT_LABEL_ROTATION` parameter above 89°

### Versions

QGIS Server 3.28.10

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by pblottiere** [comment]
Hello @nboisteault,

Actually I just noticed the same behavior with the "Rotate a Label" map tool in QGIS Desktop. I don't know if it's a feature or a bug, I'm going to take a look.

**Comment by pblottiere** [comment]
It's a feature:

![image](https://github.com/qgis/QGIS/assets/9266424/a29df5ca-4b63-4600-add0-952219e779b6)

**Comment by pblottiere** [comment]
QGIS Server highlight layers are `QgsVectorLayer` created on the fly with default options. By default, the `Show upside-down labels` option is set to `never`.

So if we want to control how labels are rendered in hilight layers in case of rotation, we probably need to add a specific option like `HIGHLIGHT_LABEL_UPSIDE_DOWN`. So it looks like a feature request more than a bug.

@nboisteault what do you think?

**Comment by nboisteault** [comment]
@pblottiere thanks a lot for your investigation. I see two things :
 - I think the behavior for the 90° rotation is a bug as it goes from clockwise at 89° to anti-clockwise at 90°
 - I understand that there might not be many use cases to have labels above 90° but if QGIS let user do that why not QGIS Server? So a `HIGHLIGHT_LABEL_UPSIDE_DOWN` parameter would be good.

**Comment by pblottiere** [comment]
Hi @nboisteault,

> I think the behavior for the 90° rotation is a bug as it goes from clockwise at 89° to anti-clockwise at 90°

It's the only way to keep the label in the right direction when the default `Show upside-down labels` option is set to `never` no? Otherwise labels will be upside-down with a 95° rotation (for example).

**Comment by nboisteault** [comment]
Hi @pblottiere ,
I mean at `90°` precisely the label should be vertical with the bottom of the line on the left. If we want a vertical label with the bottom of the line on the right, we would set `-90°`, no?
My two first screenshots show the switch from clockwise to anti-clockwise from 89° to 90°.

**Comment by pblottiere** [comment]
Hi @nboisteault,

> I mean at 90° precisely the label should be vertical with the bottom of the line on the left. If we want a vertical label with the bottom of the line on the right, we would set -90°, no?
> My two first screenshots show the switch from clockwise to anti-clockwise from 89° to 90°.

Ok I understand. I think there's something fishy in the `pal` source code but it's pretty old so maybe I'm totally wrong: https://github.com/qgis/QGIS/pull/54667

BTW, even when the *"Rotate a label*" map tool indicates `90°`, it's not perfectly true because it works with float values. You need to use the `ctrl` key to have a true `90°` angle.

**Comment by elpaso** [comment]
@pblottiere is this fixed by your PR #54667 ?

**Comment by elpaso** [comment]
> @pblottiere is this fixed by your PR #54667 ?

@pblottiere gentle ping

**Comment by pblottiere** [comment]
Hello @elpaso,

Sorry I missed your first ping... This subject is pretty old now but here is what I remember:

1. this issue is more a feature request than a bug (a new `HIGHLIGHT_LABEL_UPSIDE_DOWN` parameter would be necessary to fix it)
2. but I noticed a bug in PAL source code during the investigation (which is fixed by https://github.com/qgis/QGIS/pull/54667)

**Comment by elpaso** [comment]
@nboisteault can you please check if this is still an issue with latest QGIS master builds? If it is, can you please attach a small sample project with a small dataset and the step-by-step procedure to reproduce the issue?

**Comment by nboisteault** [comment]
I can't test with master but I've tested with QGIS Server 3.42 and the issue is still here.
