### ISSUE TITLE
Unable to edit elements in the print layout after locking an element

### ISSUE THREAD

**Issue by hblGP** [qgis/QGIS#57331]
### What is the bug or the crash?

When you group elements and locking them, and then press on the locked group afterwards you are unable to edit any other elements. It's as if all other elements gets locked as well.

### Steps to reproduce the issue

1. Open print layout
2. Add a few elements forexample labels
3. Create a group and lock it
4. Press the locked group
5. Press other elements

![qgis-ltr-bin_ztz6BurYmO](https://github.com/qgis/QGIS/assets/60741008/5fde731e-6f21-41b6-ba78-b4cef5f5ef0e)

### Versions

QGIS-version
3.34.4-Prizren
QGIS-koderevision
decd43dc
Qt version
5.15.3
Python version
3.9.18
GDAL/OGR version
3.8.4
PROJ version
9.3.1
EPSG Registry database version
v10.098 (2023-11-24)
GEOS version
3.12.1-CAPI-1.18.1
SQLite version
3.41.1
PDAL version
2.6.0
PostgreSQL klient version
16.1
SpatiaLite version
5.1.0
QWT version
6.1.6
QScintilla2 version
2.13.4
OS version
Windows 10 Version 2009

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by roya0045** [comment]
To add more details, this behaviour happens (at least on my end) when you lock ANY element in a layout.

Like other things in the layout, the situation is fixed by closing the layout and reopening it. This makes the state change behave as intended. This is probably related to a larger set of issues with state change in the layout and the complex dependencies betweeen everything. 

A refresh/reinitialization might be better for those breaking elements (atlas changes, locking and possibly some tother) than hoping the user closes and reopen the layout to 'fix' it manually.

**Comment by DelazJ** [comment]
Assuming I understood the report correctly and following the test I did here (3.36), the issue I see is that you are unable to graphically SELECT an item in the print layout once you have locked any item in the layout. Unlocking the item by unchecking the box or using the corresponding buttons does not fix the issue. Like if the "Select/move item" tool has been deactivated from interacting with the layout or ALL the items have been locked.

However it is technically still possible to edit elements. Locked items can be selected by clicking on their name in the "Items" panel and editing their properties is still possible. The issue is on selecting with the "select/move item" tool not about editing the items properties, as implied by the report title.

**Comment by elpaso** [comment]
For the record, this warning appears when clicking on the locked group and triggers the issue:

cannot grab mouse while invisible

I think it's related to the group graphic item not being visible, I have a fix but I'm not 100% sure it's the right one:

```patch
diff --git a/src/gui/layout/qgslayoutviewtoolselect.cpp b/src/gui/layout/qgslayoutviewtoolselect.cpp
index b7f9fab96dc..e395e368e1b 100644
--- a/src/gui/layout/qgslayoutviewtoolselect.cpp
+++ b/src/gui/layout/qgslayoutviewtoolselect.cpp
@@ -130,6 +130,12 @@ void QgsLayoutViewToolSelect::layoutPressEvent( QgsLayoutViewMouseEvent *event )
     return;
   }
 
+  if ( selectedItem->isLocked() )
+  {
+    //locked items cannot be selected
+    return;
+  }
+
   if ( ( event->modifiers() & Qt::ShiftModifier ) && ( selectedItem->isSelected() ) )
   {
     //SHIFT-clicking a selected item deselects it

```

I am making a PR with the patch.
