### ISSUE TITLE
Missing Update operation for WFS layers without geometry

### ISSUE THREAD

**Issue by gisuser0** [qgis/QGIS#60185]
### What is the bug or the crash?

Only Query, Insert and Delete are allowed for WFS layers without geometry. The Update operation is not available.

### Steps to reproduce the issue

1. load any table without geometry into a QGIS project and enable all the WFS capabilities: Insert, Update and Delete (Project -> Properties -> QGIS Server -> WFS/OAPIF tab)
2. publish the project with QGIS-Server
3. Query, Insert and Delete are listed in the Operations of the WFS getCapabilities but Update is missing
4. open the layer with a WFS client (e.g. QGIS Desktop) and try to edit it: you can query, create and delete features but you can't update them

### Versions

3.34.14 LTR (Windows and Linux)
3.40.2  (Windows and Linux)

### Supported QGIS version

- [x] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [x] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

Looking into the code it seems like the Update operation always requires the change geometry capability (Qgis::VectorProviderCapability::ChangeGeometries)

**Comment by elpaso** [comment]
I cannot reproduce and I think I need more details about the aspatial layer you are testing with (can you attach a small/minimal sample?)

**Comment by gisuser0** [comment]
**Steps to reproduce the issue:**

1) Create a PostgreSQL/PostGIS database
`CREATE DATABASE testwfs;`

2) Connect to the database and create one table with geometries and one table without geometries:
 `CREATE EXTENSION IF NOT EXISTS postgis;`
`CREATE TABLE with_geom (id serial, geom geography(POINT,4326), description character varying, CONSTRAINT with_geom_pkey PRIMARY KEY (id));`
`CREATE TABLE without_geom (id serial, description character varying, CONSTRAINT without_geom_pkey PRIMARY KEY (id));`

3) Create a feature with geometry and a feature without geometry:
`INSERT INTO with_geom (geom, description) VALUES('SRID=4326;POINT(0 0)', 'With geometry');`
`INSERT INTO without_geom (description) VALUES('Without geometry');`

3) Open an empty QGIS project, connect to the database and import the two tables (check "Also list tables with no geometry" in the connection properties in order to view also the _without_geom_ table)

4) Enable all the WFS capabilities for both the layers (Project -> Properties -> QGIS Server -> WFS/OAPIF tab: check Published, Update, Insert and Delete)

5) Publish the project with QGIS-Server

6) Call the WFS getCapabilities. The _with_geom_ layer has the Update operation while the _without_geom_ layer doesn't have the Update operation

**with_geom**
```
<Name>with_geom</Name>
<Title>with_geom</Title>
<DefaultSRS>EPSG:4326</DefaultSRS>
<OtherSRS>EPSG:3857</OtherSRS>
<Operations>
<Operation>Query</Operation>
<Operation>Insert</Operation>
<Operation>Update</Operation>
<Operation>Delete</Operation>
</Operations>
```

**without_geom**
```
<Name>without_geom</Name>
<Title>without_geom</Title>
<DefaultSRS/>
<OtherSRS>EPSG:4326</OtherSRS>
<OtherSRS>EPSG:3857</OtherSRS>
<Operations>
<Operation>Query</Operation>
<Operation>Insert</Operation>
<Operation>Delete</Operation>
</Operations>
```

7) connect to the WFS service with QGIS Desktop and try to change the _description_ field in both the layers: the field in the _with_geom_ table is editable while the field in the _without_geom_ is not editable

**Comment by elpaso** [comment]
@gisuser0 for the record, the fact that you were using postgres was the missing information to be able to reproduce the issue.

**Comment by gisuser0** [comment]
Thx for the fix

**Comment by gisuser0** [comment]
It seems like the missing check ` isSpatial() ` also for the wfs transaction block the update.

**qgswfstransaction.cpp**
```
Qgis::VectorProviderCapabilities cap = provider->capabilities();
      if ( !( cap & Qgis::VectorProviderCapability::ChangeAttributeValues ) || !( cap & Qgis::VectorProviderCapability::ChangeGeometries ) )
      {
        action.error = true;
        action.errorMsg = QStringLiteral( "No capabilities to do WFS updates on layer '%1'" ).arg( typeName );
        continue;
      }
      // start editing
      vlayer->startEditing();
```

Should this solve it?

```
Qgis::VectorProviderCapabilities cap = provider->capabilities();
      if ( !( cap & Qgis::VectorProviderCapability::ChangeAttributeValues ) || !( vlayer->isSpatial() && cap & Qgis::VectorProviderCapability::ChangeGeometries ) )
      {
        action.error = true;
        action.errorMsg = QStringLiteral( "No capabilities to do WFS updates on layer '%1'" ).arg( typeName );
        continue;
      }
      // start editing
      vlayer->startEditing();
```

**Comment by elpaso** [comment]
@gisuser0 yes: that needs the same changes, I am sorry: I only checked the getcapabilities and I assumed the transaction part was ok. I will make another PR for that.

**Comment by elpaso** [comment]
@gisuser0 this should fix the last issue: https://github.com/qgis/QGIS/pull/60273

**Comment by gisuser0** [comment]
Is it possible to backport also the fix https://github.com/qgis/QGIS/pull/60273 to the LTR 3.40?
The fix https://github.com/qgis/QGIS/pull/60266 was backported to the 3.40 but without the https://github.com/qgis/QGIS/pull/60273 the issue still occours in the LTR (only the 3.42 is full-fixed).
Thx

**Comment by nicolas-sitylb** [comment]
Hello,
@elpaso : could this fix be also backported to the QGIS 3.34.x series, if it hasn't already been done?
We are encountering this same problem in an environment still based on QGIS 3.34.
Thanks.

--

Edit: 
I've check that with @m-kuhn and he told me this will not be backported to 3.34 due to the end-of-life of this version.
You can therefore consider this message null and void.
