### ISSUE TITLE
WMS and XYZ Tiles Not Displaying in Project CRS (EPSG:5514) After Updating QGIS

### ISSUE THREAD

**Issue by vrabecmarekradovan** [qgis/QGIS#60807]
### What is the bug or the crash?

After updating QGIS to the latest LTS version, which is currently 3.40.4 Bratislava, WMS and XYZ tile layers that are in CRS EPSG:3857 do not display at all when the project CRS is set to EPSG:5514 (or its newer realisation EPSG:8353, which are both standard in Slovakia). The layers only appear if the project CRS is changed to match the CRS of the WMS or XYZ tiles, so EPSG:3857 for most of them. This issue is also present in 3.42.0 version. This behavior was not present in QGIS 3.38.3, where on-the-fly CRS transformation worked as expected. I replicated this issue on multiple devices, including clean install of both affected versions of QGIS.

### Steps to reproduce the issue

1. Set the project CRS to EPSG:5514 (or EPSG:8353)
2. Add a WMS or XYZ tile layer with a different CRS (e.g. OpenStreetMap ttps://tile.openstreetmap.org/{z}/{x}/{y}.png)
3. Observe that the layer does not display in the map canvas.
4. Change the project CRS to match the layer's CRS (e.g., EPSG:3857), and the layer appears correctly.

### Versions

Issue was spotted in LTR version 3.40.4, but the latest version 3.42.0 is also affected. Version 3.38.3 works as expected. Other versions were not tested.

### Supported QGIS version

- [x] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [x] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
Hi @nyalldawson, this issue seems very similar to the ones already previously fixed by you, but it looks like this issue has not been fixed by https://github.com/qgis/QGIS/pull/60759.

**Comment by Utilitra2024** [comment]
I am encountering this exact same issue, however am using different CRS from the original poster. Also using QGIS LTR 3.40.4

**Comment by walking-the-talk** [comment]
This also occurs with EPSG 27700 - the tiles appear as soon as the project CRS is set to EPSG 3857. 

I'm not sure if it is related, but if I set the project CRS to EPSG 4326 none of the vector layers that have EPSG 27700 CRS disappear from the canvas. Zoom to layer extent does not work, but Zoom to Full extent does (and shows the XYZ tiles). 

Another side note on this is that if an 'online' layer is added to the project through OpenLayers Plugin, the XYZ tiles then appear without changing the project CRS, which seems a bit strange, but is a temporary work-around for EPSG 27700 projects. The XYZ tiles remain visible after the OpenLayers layer is removed from the canvas, but next time the project is loaded the XYZ tiles are invisible...

I have just updated from LTR 3.34.10 to LTR 3.40.4

**Comment by agiudiceandrea** [comment]
@walking-the-talk such issue has been already reported and fixed. Please check running QGIS 3.43.0-Master or the next upcoming QGIS LTR 3.40.5.

**Comment by frasemcl** [comment]
Sounds like there is a good chance this will have been fixed already, but I'm having an issue displaying XYZ tiles in:
- ESRI:102184

Before update to most recent LTR these two services and others were working as expected in this proj:
- **Name:** OpenStreetMap, **URL:** https://tile.openstreetmap.org/{z}/{x}/{y}.png
- **Name:** ESRI Hillshade, **URL:** http://services.arcgisonline.com/ArcGIS/rest/services/Elevation/World_Hillshade/MapServer/tile/{z}/{y}/{x}


Happy to provide more info if that would be helpful.

**Comment by agiudiceandrea** [comment]
@vrabecmarekradovan, indeed, as I indicated in my first comment, the issue you are experiencing has not yet been fixed. On the contrary, the issues reported in previous comments by @walking-the-talk and @frasemcl have been already fixed.

**Comment by CharlesGag** [comment]
Same thing for me using 3.42.0 and EPSG:3798. This projet used to work fine before the update.

**Comment by agiudiceandrea** [comment]
@CharlesGag, the issue with CRS EPSG:3798 has been already fixed.

**Comment by agiudiceandrea** [comment]
@nyalldawson, have you had the chance to look a this issue report about EPSG:5514 and EPSG:8353? This issue still occurs on Master even after your PR https://github.com/qgis/QGIS/pull/60759.

**Comment by QuestingVole** [comment]
Can confirm this is broken in 3.42 but fixed (at least for EPSG:27700) in 3.43 Master.

I noticed "Zoom To Layer(s)" was also broken in mixed CRS projects (it Zoomed to the extent given in layer CRS coordinates rather than project CRS coordinates) but this is also fixed in 3.43.  I assume the two problems were related.
