### ISSUE TITLE
Elevation profile duplicates layers in its layer tree if new layers are added in project with elevation profile active

### ISSUE THREAD

**Issue by ViperMiniQ** [qgis/QGIS#63934]
### What is the bug or the crash?

If Elevation Profile is active when new layers are added in the project, they get duplicated in the Elevation profile layer tree.

https://github.com/user-attachments/assets/cf720960-79b6-4912-8235-19ac78a2dbdc

### Steps to reproduce the issue

1.) Add New Elevation Profile
2.) Add new layer to project
3.) Observe duplicated layer in Elevation Profile layer tree

### Versions

<table width='100%' align='center'><tr><td>QGIS version</td><td>3.99.0-Master</td></tr><tr><td>QGIS code revision</td><td><a href="https://github.com/qgis/QGIS/commit/d0cffafe70f">d0cffafe70f</a></td></tr><tr><td colspan="2">&nbsp;</td></tr><tr><td colspan="2"><b>Libraries</b></td></tr><tr><td>Qt version</td><td>6.9.3</td></tr><tr><td>Python version</td><td>3.13.9</td></tr><tr><td>GDAL version</td><td>3.10.3</td></tr><tr><td>PROJ version</td><td>9.6.2</td></tr><tr><td>EPSG Registry database version</td><td>v12.013 (2025-05-26)</td></tr><tr><td>GEOS version</td><td>3.13.0-CAPI-1.19.0</td></tr><tr><td>SFCGAL version</td><td>No support</td></tr><tr><td>SQLite version</td><td>3.47.2</td></tr><tr><td>PDAL version</td><td>2.8.4</td></tr><tr><td>PostgreSQL client version</td><td>16.9</td></tr><tr><td>SpatiaLite version</td><td>5.1.0</td></td></tr><tr><td>QWT version</td><td>6.2.0</td></tr><tr><td>QScintilla2 version</td><td>2.14.1</td></tr><tr><td>OS version</td><td>Fedora Linux 42 (KDE Plasma Desktop Edition)</td></tr><tr><td colspan="2"><i>This copy of QGIS writes debugging output.</i></td></tr><tr><td colspan="2">&nbsp;</td></tr><tr><td colspan="2"><b>Active Python plugins</b></td></tr><tr><td>db_manager</td><td>0.1.20</td></tr><tr><td>processing</td><td>2.12.99</td></tr><tr><td>grassprovider</td><td>2.12.99</td></tr><tr><td>MetaSearch</td><td>0.3.6</td></tr></table>

### Supported QGIS version

- [x] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [x] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by ViperMiniQ** [comment]
Also, not sure if intended, but if layers are dragged from the elevation profile layer tree, they are also removed from the project completely.

https://github.com/user-attachments/assets/a4719f32-37e6-4c19-8e93-9b1b57185814

**Comment by ptitjano** [comment]
@ViperMiniQ Thanks for the report, I can reproduce the issue. This regression was introduced by this PR: #63876 

Indeed, a new layer is now added 2 times to the elevation tree:
- first by the call to ` mLayerTreeView->populateMissingLayers( QgsProject::instance() )` (introduced by #63876) 
- a second time by the `QgsLayerTreeRegistryBridge` of the `QgsElevationProfileWidget`.

I'm not sure how to fix this issue though, because I don't know in which cases the issues solved by the previous PR actually occurred.

@nyalldawson Could you please explain which cases the previous PR addressed?

**Comment by nyalldawson** [comment]
@ptitjano it's already on my radar, but I'm at foss4g this week. I'll look when I'm back in the office

**Comment by ViperMiniQ** [comment]
It also happens if you `Right click` -> `Duplicate` from the Layers Panel.

**Comment by ViperMiniQ** [comment]
@nyalldawson 

This is still happening when drag'n'dropping layers with the elevation profile open.
It does not happen on duplicate call anymore.
